apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloudstack-csi-controller
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cloudstack-csi-controller-role
rules:
  - apiGroups: [""]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "update"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["patch"]
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "create", "delete", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "watch", "list", "delete", "update", "create"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["storageclasses", "csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments/status"]
    verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cloudstack-csi-controller-binding
subjects:
  - kind: ServiceAccount
    name: cloudstack-csi-controller
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cloudstack-csi-controller-role
  apiGroup: rbac.authorization.k8s.io
---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cloudstack-csi-node
  namespace: kube-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudstack-csi-node-role
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "patch"]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "volumeattachments" ]
    verbs: [ "get", "list", "watch" ]
  - apiGroups: [ "storage.k8s.io" ]
    resources: [ "csinodes" ]
    verbs: [ "get" ]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cloudstack-csi-node-binding
subjects:
  - kind: ServiceAccount
    name: cloudstack-csi-node
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cloudstack-csi-node-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: csi.cloudstack.apache.org
spec:
  attachRequired: true
  podInfoOnMount: false
  # Supports only persistent volumes.
  volumeLifecycleModes:
    - Persistent
---
# In this YAML file CloudStack CSI Controller contains the following sidecars:
# external-attacher, external-provisioner, external-resizer, liveness-probe
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudstack-csi-controller
  namespace: kube-system
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudstack-csi-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudstack-csi-controller
        app.kubernetes.io/part-of: cloudstack-csi-driver
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: cloudstack-csi-controller
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app.kubernetes.io/name"
                operator: In
                values:
                - cloudstack-csi-controller
            topologyKey: "kubernetes.io/hostname"
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node-role.kubernetes.io/control-plane
                operator: Exists
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: CriticalAddonsOnly
          operator: Exists
        - effect: NoExecute
          operator: Exists
          tolerationSeconds: 300
      securityContext:
        runAsNonRoot: true
        runAsUser: 65532
        runAsGroup: 65532
        fsGroup: 65532
        fsGroupChangePolicy: OnRootMismatch

      containers:
        - name: cloudstack-csi-controller
          image: cloudstack-csi-driver
          imagePullPolicy: Always
          args:
            - "controller"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloudstack-config=/etc/cloudstack-csi-driver/cloud-config"
            - "--logging-format=text"
            - "--v=4"
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
            - name: cloudstack-conf
              mountPath: /etc/cloudstack-csi-driver
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          resources:
            requests:
              cpu: 10m
              memory: 40Mi
            limits:
              memory: 256Mi
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        - name: external-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v5.0.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
            - "--leader-election"
            - "--leader-election-lease-duration=120s"
            - "--leader-election-renew-deadline=60s"
            - "--leader-election-retry-period=30s"
            - "--default-fstype=ext4"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        - name: external-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.6.1
          imagePullPolicy: IfNotPresent
          args:
            - "--v=4"
            - "--timeout=300s"
            - "--csi-address=$(ADDRESS)"
            - "--leader-election"
            - "--leader-election-lease-duration=120s"
            - "--leader-election-renew-deadline=60s"
            - "--leader-election-retry-period=30s"
            - "--kube-api-qps=100"
            - "--kube-api-burst=100"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        - name: external-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.11.1
          args:
            - "--v=5"
            - "--csi-address=$(ADDRESS)"
            - --timeout=300s
            - --leader-election
            - --leader-election-lease-duration=120s
            - --leader-election-renew-deadline=60s
            - --leader-election-retry-period=30s
            - --kube-api-qps=100
            - --kube-api-burst=100
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            seccompProfile:
              type: RuntimeDefault
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: cloudstack-conf
          secret:
            secretName: cloudstack-secret
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudstack-csi-node
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cloudstack-csi-node
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: "10%"
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cloudstack-csi-node
        app.kubernetes.io/part-of: cloudstack-csi-driver
    spec:
      priorityClassName: system-node-critical
      serviceAccountName: cloudstack-csi-node
      nodeSelector:
        kubernetes.io/os: linux
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          operator: Exists
        - effect: NoExecute
          operator: Exists
          tolerationSeconds: 300
      securityContext:
        runAsNonRoot: false
        runAsUser: 0
        runAsGroup: 0
        fsGroup: 0

      containers:
        - name: cloudstack-csi-node
          image: cloudstack-csi-driver
          imagePullPolicy: IfNotPresent
          args:
            - "node"
            - "--endpoint=$(CSI_ENDPOINT)"
            - "--cloudstack-config=/etc/cloudstack-csi-driver/cloud-config"
            - "--logging-format=text"
            - "--node-name=$(NODE_NAME)"
            - "--v=4"
          env:
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: kubelet-dir
              mountPath: /var/lib/kubelet
              # needed so that any mounts setup inside this container are
              # propagated back to the host machine.
              mountPropagation: Bidirectional
            - name: device-dir
              mountPath: /dev
            - name: cloud-init-dir
              mountPath: /run/cloud-init/
            # Comment the above 2 lines and uncomment the next 2 lines for Ignition support
            # - name: ignition-dir
            #   mountPath: /run/metadata
            - name: cloudstack-conf
              mountPath: /etc/cloudstack-csi-driver
          ports:
            - name: healthz
              containerPort: 9808
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 10
            failureThreshold: 5
          resources:
            limits:
              cpu: "200m"
              memory: 200Mi
            requests:
              cpu: "50m"
              memory: 50Mi
          securityContext:
            # readOnlyRootFilesystem: true
            privileged: true

        - name: node-driver-registrar
          image: registry.k8s.io/sig-storage/csi-node-driver-registrar:v2.10.1
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)"
            - "--v=5"
            - "--health-port=9809"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
            - name: DRIVER_REG_SOCK_PATH
              value: /var/lib/kubelet/plugins/csi.cloudstack.apache.org/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
            - name: registration-dir
              mountPath: /registration
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            exec:
              command:
                - /csi-node-driver-registrar
                - --kubelet-registration-path=$(DRIVER_REG_SOCK_PATH)
                - --mode=kubelet-registration-probe
            initialDelaySeconds: 30
            periodSeconds: 90
            timeoutSeconds: 15
          resources:
            limits:
              cpu: "200m"
              memory: 200Mi
            requests:
              cpu: "50m"
              memory: 50Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

        - name: liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.12.0
          imagePullPolicy: IfNotPresent
          args:
            - "--v=4"
            - "--csi-address=$(ADDRESS)"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: plugin-dir
              mountPath: /csi
          resources:
            limits:
              cpu: "200m"
              memory: 250Mi
            requests:
              cpu: "50m"
              memory: 50Mi
          securityContext:
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false

      volumes:
        - name: plugin-dir
          hostPath:
            path: /var/lib/kubelet/plugins/csi.cloudstack.apache.org/
            type: DirectoryOrCreate
        - name: kubelet-dir
          hostPath:
            path: /var/lib/kubelet
            type: Directory
        - name: device-dir
          hostPath:
            path: /dev
            type: Directory
        - name: registration-dir
          hostPath:
            path: /var/lib/kubelet/plugins_registry
            type: Directory
        - name: cloud-init-dir
          hostPath:
            path: /run/cloud-init/
            type: Directory
        # Comment the above 4 lines and uncomment the next 4 lines for Ignition support
        # - name: ignition-dir
        #   hostPath:
        #     path: /run/metadata
        #     type: Directory
        - name: cloudstack-conf
          secret:
            secretName: cloudstack-secret
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: cloudstack-custom
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: csi.cloudstack.apache.org
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: false
parameters:
  csi.cloudstack.apache.org/disk-offering-id: 32b444d6-06b7-4ecb-acff-7f8e202ec68b
